### ISSUE TITLE
DEFAULT_METHOD_WHITELIST is outdated as requests library does not pin urllib3 to a version

### ISSUE THREAD

**Issue by eric-french** [smartsheet/smartsheet-python-sdk#32]
Requests library used in Smartsheet's Python SDK does not pin urllib3 to a version; resulting in inconsistent behavior as SDK may subsequently useold version of urllib3 depending on which platform it was installed.

Expected Result
No error when using the allowed_methods param with Retry

Actual Result
`AttributeError: type object 'Retry' has no attribute 'DEFAULT_METHOD_WHITELIST'`

Reproduction Steps
1. `pip install smartsheet-python-sdk` which will pull in this code: https://github.com/smartsheet/smartsheet-python-sdk/blob/8a7b8f39d31a9dca8b2a80773cac1baa8a95bd38/smartsheet/session.py#L56
2. `pip install urllib3==2.0.2` which is a known version that reproduces this issue 
3. `smar_client = smartsheet.Smartsheet(smartsheet_api_token)` which is code to invoke new Smartsheet API connection

**Comment by TarekSalha** [comment]
same issue, this killed one of my services today at deployment

**Comment by Rurquhart** [comment]
FYI @TarekSalha this should be fixed in `v3.0.2` of the SDK
