### ISSUE TITLE
Add the ability to update rows 

### ISSUE THREAD

**Issue by green3g** [smartsheet/smartsheet-python-sdk#33]
**Is your feature request related to a problem? Please describe.**

Currently, I can't find a way to use the update rows operation on a sheet. This would be a useful enhancement because I often need to check for existing rows, update them if they exist, or add a new row if they do not exist. 

**Describe the solution you'd like**

I think this would be a nice interface to add:

```python
row = sheet.rows[0]
row.cells[0].value = 'new value'

# enhance the sheet object allowing us to call update_rows
sheet.update_rows([row])
```

**Additional context**

**Comment by green3g** [comment]
I've found a way to do this using the SDK, I just couldn't find this in the python docs. Hopefully this helps someone else down the road. 

```py
def update_row(sheet, row: smart.models.Row, row_dict: dict, mapping: dict):
    new_row = smartsheet.models.Row()
    new_row.id = row.id_

    for key in row_dict.keys():
        cell = smartsheet.models.Cell()
        cell.column_id = mapping[key]
        cell.value = row_dict[key]
        new_row.cells.append(cell)
    
    return smart.Sheets.update_rows(sheet.id_, [new_row])
```

**Comment by brockhaywood** [comment]
@green3g thanks for this but what a bad developer experience.
